version: 2
updates:
  - package-ecosystem: gomod
    directory: /web
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: monthly
    groups:
      frontend:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
